### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by PatrickHeneise** [nodeschool/barcelona#1]
Suggestions and comments here please!

**Comment by PatrickHeneise** [comment]
Thanks to @fhemberger for the submission

![](https://raw.githubusercontent.com/nodeschool/barcelona/master/images/nodeschool-barcelona.png)

**Comment by BelenPoyo** [comment]
New Submission![nodeschool barcelona](https://cloud.githubusercontent.com/assets/14564047/9992192/ad68082c-6046-11e5-9d4d-4d7d8ee4bc20.jpg)

**Comment by fhemberger** [comment]
Yay, **much** better than my quick Inkscape adventure. ;)
Colors could be a bit more saturated though, I used the color values of the Catalan flag from Wikipedia (not sure how "official" those colors are).

**Comment by BelenPoyo** [comment]
Yes, this are the same colors that wikipedia said as oficial from the spain flag. I will find a better combination that don't punch us in the eye, haha.
And i was thinking to make one more logo with the batllo house, but to be honest sagrada familia is more representative of barcelona.

**Comment by BelenPoyo** [comment]
New shape, new color![new shape new color](https://cloud.githubusercontent.com/assets/14564047/10024464/b85ecddc-612d-11e5-9c83-f32dfb3af733.png)

**Comment by BelenPoyo** [comment]
![new color nodes](https://cloud.githubusercontent.com/assets/14564047/10033906/b399ee5a-6162-11e5-93eb-eb6681ce2f4f.png)
