### ISSUE TITLE
Call for Mentors: Nov 14

### ISSUE THREAD

**Issue by PatrickHeneise** [nodeschool/barcelona#11]
We have a space for about 30 people for NodeSchool, from 10:30 to 14:00.

Venue: SkyScanner - Plaza Catalunya 1, 5ta planta Módulos AB

Date: November 14

Volunteers needed: 4-6

If you can commit to this event leave a comment on this issue. 

I'll update this list as we get more mentors.
### Mentors:
- [x] @patrickheneise
- [x] @eth0lo 
- [x] @dmitry-zaets
- [x] @Moezalez
- [x] @javiertejero
- [ ] @janmyler
### Organisers:
- [x] @barcelonajs

Read the [NodeSchool Event Mentor Best Practices Guide](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) before the event.

**Comment by ghost** [comment]
I'd like to help out

**Comment by javiertejero** [comment]
I'd like to be a mentor

**Comment by dmitry-zaets** [comment]
+1

**Comment by PatrickHeneise** [comment]
Please check the feedback from the last session. 

https://github.com/nodeschool/barcelona/blob/master/feedback/feedback-oct-4.csv

Any ideas on the "more active mentoring" and "group work" comments?

**Comment by dmitry-zaets** [comment]
For a group work I will suggest a small assessment (test-like, 5 minutes and about 10-15 questions). So we will be able to determine skills level for each individual person and make pairs.

**Comment by ghost** [comment]
Random idea: Maybe create a small subsets of people, assign them a mentor, and everyone can introduce themselves to each other (including the mentor). 

I feel like if people would be a little bit more acquainted with each other and at least know each others names, they rather would ask each other (and the mentor) for help and work together.

**Comment by eth0lo** [comment]
I'll go as well

**Comment by janmyler** [comment]
I'd like to help with mentoring as well.

**Comment by janmyler** [comment]
Hello everyone, I got an appointment at the dentist for my wisdom teeth removal on Friday 13th. I'm not sure I'll be able to attend and help as a mentor this time.

**Comment by PatrickHeneise** [comment]
Ok, thanks!
