### ISSUE TITLE
Call for mentors: Dec 19 @ SkyScanner

### ISSUE THREAD

**Issue by PatrickHeneise** [nodeschool/barcelona#15]
We have a space for about 30 people for NodeSchool, from 10:30 to 14:00 at SkyScanner - Plaza Catalunya 1, 5ta planta Módulos AB on December 19.

Volunteers needed: 4-6

Tickets: https://ti.to/barcelonajs/nodeschool-3

If you can commit to this event leave a comment on this issue. 

I'll update this list as we get more mentors.
### Mentors:
- [x] @patrickheneise
- [ ] @eth0lo 
- [ ] @carleskapy
- [x] @ifraixedes
- [x] @dmitry-zaets
- [ ] @Moezalez
- [ ] @janmyler
- [ ] ?

Read the [NodeSchool Event Mentor Best Practices Guide](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) before the event.

**Comment by ifraixedes** [comment]
@PatrickHeneise I'll be there

**Comment by dmitry-zaets** [comment]
+1

**Comment by javiertejero** [comment]
@PatrickHeneise please remove me from the list, can't confirm yet if I'll be able to assist this time. I just committed to the previous Node School, apologies for the misunderstanding.

If I change my mind I'll let you know.

**Comment by ghost** [comment]
Unfortunately I'll be in Germany on that day, but I'd like to volunteer the next time!

**Comment by CarlesKapy** [comment]
I won't be on Barcelona on Dec 19. Maybe next time ;)

2015-11-30 18:13 GMT+00:00 Moritz Sattler notifications@github.com:

**Comment by steffen** [comment]
@PatrickHeneise Add me to the list. I'll have to leave a little bit earlier though (around 13:30).

**Comment by janmyler** [comment]
@PatrickHeneise I'm already out of Barcelona for Christmas.

**Comment by PatrickHeneise** [comment]
@janmyler the event was last week :P

**Comment by janmyler** [comment]
@PatrickHeneise I also realized that some time after commenting. :smile:
