### ISSUE TITLE
Charging 5,- for NodeSchool?

### ISSUE THREAD

**Issue by PatrickHeneise** [nodeschool/barcelona#17]
NodeSchool London started charging £5 to attend NodeSchool. 

I'd like to open the discussion what you think about this for NodeSchool Barcelona?

Every 5€ charge means:
- 10ct ti.to fees
- 32ct credit card fees

In the last 3 events, from 30 registered tickets, there were 15-20 people, that's 40-50% NO-SHOW. Charging for the event would mean 100% show rate, that makes planning mentors and venues a lot easier.

The event would still remain non-profit. 100% of the income would be used to get snacks and other perks.

Opinions? Any ideas how to decrease the NO-SHOW rate without adding a charge?

**Comment by mikeal** [comment]
It's pretty common in meetups and whatnot to charge a small fee as a commitment device. This is becoming pretty widely used, and you can always give a discount code to someone you know will show up and doesn't have the money.

**Comment by PatrickHeneise** [comment]
What me worries most is the fee. 42ct for such a small fee is quite expensive.

**Comment by dmitry-zaets** [comment]
I agree that it is a good idea and it will increate percentage of show rate.
But fee is big as for me as well, can't we use another service for this? (PayPal?)

**Comment by padrisimo** [comment]
What about not make it than early in the morning on Saturday when everybody is hangover?

**Comment by PatrickHeneise** [comment]
@dmitry-zaets paypal is even more and they don't issue invoices for the fees they take.

@padrisimo that belongs into https://github.com/nodeschool/barcelona/issues/16
