### ISSUE TITLE
Call for mentors: April 30 @ SkyScanner

### ISSUE THREAD

**Issue by PatrickHeneise** [nodeschool/barcelona#19]
We have a space for about 30 people for NodeSchool, from 11:00 to 14:00 at SkyScanner - Plaza Catalunya 1, 5ta planta Módulos AB on April 30.

Volunteers needed: 4-6

Tickets: https://ti.to/nodeschool-barcelona/nodeschool-april-2016

If you can commit to this event leave a comment on this issue. 

I'll update this list as we get more mentors.
### Mentors:
- [x] @pchiwan 
- [ ] @patrickheneise
- [ ] @eth0lo 
- [ ] @carleskapy
- [ ] @ifraixedes
- [ ] @dmitry-zaets
- [ ] @Moezalez
- [ ] @janmyler
- [x] @dasilvacontin 
- [x] @xicombd
- [x] @ifraixedes 

Read the [NodeSchool Event Mentor Best Practices Guide](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) before the event.

**Comment by ghost** [comment]
I'd like to but I'll be visiting in Germany!
Next time!

**Comment by dmitry-zaets** [comment]
Unfortunately, at this date I will be out of Spain.

**Comment by janmyler** [comment]
Sorry, I'm also out of Spain that day.

**Comment by adabcnjs** [comment]
I'm in! I've already registered a ticket and 3 more girls from adaJS are joining too ;)

**Comment by fbaiodias** [comment]
I can help, too :)

**Comment by ifraixedes** [comment]
I'll join

**Comment by dasilvacontin** [comment]
If you still need extra mentors, sign me up. :)

**Comment by xescugc** [comment]
Sorry guys but the 30 I'm out, @PatrickHeneise i would really like to be there sorry ... :cry:

**Comment by steffen** [comment]
I would have loved to, but I'm out of country that weekend. :(

**Comment by PatrickHeneise** [comment]
Thanks all! That should definitely be enough :)
