### ISSUE TITLE
NodeSchool International Day, May 21 @ SkyLab Academy

### ISSUE THREAD

**Issue by PatrickHeneise** [nodeschool/barcelona#20]
We have a space for about 25 people for NodeSchool, from 11:00 to 15:00 at SkyLab Coders Academy - Plaça Reial 18, 2nd floor, on May 21.

Volunteers needed: 4-6

Tickets: https://ti.to/nodeschool-barcelona/nodeschool-international-day

If you can commit to this event leave a comment on this issue. 

I'll update this list as we get more mentors.
### Mentors:
- [x] @pchiwan 
- [x] @patrickheneise
- [ ] @carleskapy
- [x] @dmitry-zaets
- [ ] @Moezalez
- [ ] @janmyler
- [x] @dasilvacontin 
- [ ] @xicombd
- [x] @ifraixedes 
- [x] @Gpx 

Read the [NodeSchool Event Mentor Best Practices Guide](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) before the event.

**Comment by dmitry-zaets** [comment]
Great! I'm in!

**Comment by pchiwan** [comment]
I'm in too!

**Comment by dasilvacontin** [comment]
@ifraixedes is twice on the list 😄

I'm not sure I can attend – will update when I know so.

**Comment by ifraixedes** [comment]
I'm omnipresent for that reason I'm twice 😄 

Unfortunately, I cannot attend this time, so my omnipresence is fake!

**Comment by ifraixedes** [comment]
The plan has changed; I may be able to help, but I'm still not sure, I'll update later this week

**Comment by dasilvacontin** [comment]
Update: count me in. :)

**Comment by Gpx** [comment]
Hi, I attended at the last NodeSchool. I would like to help out with this one :)

**Comment by PatrickHeneise** [comment]
Great :)

**Comment by ifraixedes** [comment]
I'll join, but I may have to leave an hour before the ending time.

**Comment by Gpx** [comment]
Hey, what time should I be there tomorrow?

**Comment by ifraixedes** [comment]
I think that 10 minutes before the event should be enough

@PatrickHeneise do we need to arranges tables or prepare the room?

**Comment by xescugc** [comment]
Hi! I'll be also there, I forgot to do it via Titto is there any problem? 😢

**Comment by PatrickHeneise** [comment]
@XescuGC: no problem

@Gpx @ifraixedes: no need to prepare anything. I'll be there around 10.45.
