### ISSUE TITLE
Next event?

### ISSUE THREAD

**Issue by PatrickHeneise** [nodeschool/barcelona#24]
Calling previous mentors @pchiwan @eth0lo @CarlesKapy @ifraixedes @janmyler @dasilvacontin @xicombd @ifraixedes

Barcelona Code School has offered their space (12 workplaces) for NodeSchool Barcelona. If someone is interested to take this group and organise events, please reach out to @mikeal or @maxogden to get organisers permissions on this repo. Would be great to get NodeSchool back to Barcelona.

**Comment by ifraixedes** [comment]
Thanks Patrick for warning us out.

I'm currently living outside Barcelona, although I could say that's not very far (70km). I may get some time to help but I have one inconvenient more than before.

**Comment by PatrickHeneise** [comment]
It's not a warning, just info ;)

**Comment by ifraixedes** [comment]
I didn't mean warning as we can interpret in log file 😂
