### ISSUE TITLE
Attendees waiting list?

### ISSUE THREAD

**Issue by janmyler** [nodeschool/barcelona#7]
Hi, just noticed there is a sign-up for the first NodeSchool and it looks like all the places are taken already. Is it serious or will it be fine to come anyway and just sit down somewhere on the floor…?

**Comment by PatrickHeneise** [comment]
Hi @janmyler, I'll let you know by next week, maybe some people void their tickets. The space has limited capacity and we have very few mentors. As it's the first event, we'll hope to have more mentors and bigger space available soon.

**Comment by janmyler** [comment]
Thanks @PatrickHeneise!
