### ISSUE TITLE
Call for mentors: Oct 3 @ SkyScanner

### ISSUE THREAD

**Issue by PatrickHeneise** [nodeschool/barcelona#8]
We have a space for about 30 people for NodeSchool, from 10:30 to 14:00 at SkyScanner - Plaza Catalunya 1, 5ta planta Módulos AB on October 3rd. 

Volunteers needed: 4-6

If you can commit to this event leave a comment on this issue. 

I'll update this list as we get more mentors.
### Mentors:
- [x] @patrickheneise
- [x] @eth0lo 
- [x] @carleskapy
- [x] @ifraixedes
- [x] @dmitry-zaets
- [ ] ?

Read the [NodeSchool Event Mentor Best Practices Guide](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) before the event.

**Comment by dmitry-zaets** [comment]
Hi,
I would like to be a volunteer on this event.
Regards,
Dmitry.

**Comment by PatrickHeneise** [comment]
Thanks all. Here's the feedback. https://barcelonajs.typeform.com/report/X33RcO/ex6H
